version: "3.8"

services:
  div-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LIGHTHOUSE_API_KEY=${LIGHTHOUSE_API_KEY}
      - WEB3_PROVIDER_URL=${WEB3_PROVIDER_URL}
      - VAULT_CONTRACT_ADDRESS=${VAULT_CONTRACT_ADDRESS}
      - USDC_CONTRACT_ADDRESS=${USDC_CONTRACT_ADDRESS}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
